[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
# memory_limit = 10000000000000000
# gas_limit = "299554432"

remappings = [
    "@bloom-v2/=src/",
    "@solady/=lib/solady/src/",
    "@chainlink/=lib/chainlink/contracts/src/v0.8/",
]



[fuzz]
runs = 10000

[invariant]
runs = 10
depth = 100
fail_on_revert = true


gas_reports = ["*"]
gas_reports_ignore = ["MockERC20", "BloomTestSetup"]

[rpc_endpoints]
arbitrum = "${ARB_RPC_URL}"
arbitrum_sepolia = "${ARB_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBITRUM_API_KEY}" }
arbitrum_sepolia = { key = "${ARBITRUM_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }